[package]
name = "pidfd2"
description = "Safe interface for Linux pidfds"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.30.1", features = ["process", "signal"] }

[dev-dependencies]
rand = "0.9.1"
